### ISSUE TITLE
/server breaks with weirdly named servers

### ISSUE THREAD

**Issue by Xavyrr** [NatTupper/Discline-curses#3]
Using `/ server` with a server that has a name with some symbols causes discline to throw an error.

> /server filTask exception was never retrieved
                                                         future: <Task finished coro=<draw_screen() done, defined at /home/xavyrr/Discline/ui/ui.py:264> exception=error('wmove() returned ERR',)>
                                  Traceback (most recent call last):
                                                                      File "/home/xavyrr/Discline/ui/ui.py", line 277, in draw_screen
                                                         await draw_left_bar()
                                                                                File "/home/xavyrr/Discline/ui/ui.py", line 378, in draw_left_bar
                                                                     leftBar.move(idx,0)
        _curses.error: wmove() returned ERR

The server name I'm trying to switch to is called `FILTEЯ.exe`
I'm guessing the backwards R is causing the the issue when discline tries to match my /s command argument.

**Comment by NatTupper** [comment]
Looking into it.

**Comment by NatTupper** [comment]
Sorry about the delay. Trying to fix it in testing branch now.

**Comment by NatTupper** [comment]
Update: Was able to get some odd results working in testing branch, but I could not replicate the bug in master. Were you using testing or master? And if it was testing, could you try master to see if the bug still applies? If it does, it's something to do with the channel names as the error complains about the left bar not drawing stuff correctly.

**Comment by NatTupper** [comment]
Cannot replicate bug and user did not reply to the thread.
